server:
  port: 8080

spring:
  datasource:
    druid:
      username: root
      password: root
      url: jdbc:mysql://localhost:3306/car_rental?serverTimezone=GMT%2B8

  thymeleaf:
    cache: false
    prefix: classpath:/templates/  
    suffix: .html                 

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
      location: ${file.upload-dir}/temp

  # mvc:
  #   static-path-pattern: /**
  #   hiddenmethod:
  #     filter:
  #       enabled: true
  mvc:
    static-path-pattern: /images/**
    # hiddenmethod:
    #   filter:
    #     enabled: true
  # web:
  #   resources:
  #     static-locations:
  #       - classpath:/static/
  #       - file:${file.upload-dir}
  web:
  resources:
    static-locations:
      - classpath:/static/
      - file:D:/upload/


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wut.zn.entity
  configuration:
    map-underscore-to-camel-case: true

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: pageNum=startPage,pageSize=pageSize

file:
  upload-dir: D:/upload/   